"""create kadan_transaction  table

Revision ID: 6053463cbe25
Revises: ca13bb82256d
Create Date: 2026-09-11 00:10:05.578718
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6053463cbe25'
down_revision: Union[str, Sequence[str], None] = 'ca13bb82256d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kadan_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kadan_account_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kadan_account_id'], ['kadan_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kadan_transactions_bill_id'), 'kadan_transactions', ['bill_id'], unique=False)
    op.create_index(op.f('ix_kadan_transactions_created_at'), 'kadan_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_kadan_transactions_created_by'), 'kadan_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_kadan_transactions_kadan_account_id'), 'kadan_transactions', ['kadan_account_id'], unique=False)
    op.create_index(op.f('ix_kadan_transactions_tenant_id'), 'kadan_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kadan_transactions_transaction_type'), 'kadan_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kadan_transactions_transaction_type'), table_name='kadan_transactions')
    op.drop_index(op.f('ix_kadan_transactions_tenant_id'), table_name='kadan_transactions')
    op.drop_index(op.f('ix_kadan_transactions_kadan_account_id'), table_name='kadan_transactions')
    op.drop_index(op.f('ix_kadan_transactions_created_by'), table_name='kadan_transactions')
    op.drop_index(op.f('ix_kadan_transactions_created_at'), table_name='kadan_transactions')
    op.drop_index(op.f('ix_kadan_transactions_bill_id'), table_name='kadan_transactions')
    op.drop_table('kadan_transactions')
    # ### end Alembic commands ###