"""create kadan_account table

Revision ID: ca13bb82256d
Revises: 6d8b5227e0da
Create Date: 2026-09-11 00:01:14.274335
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ca13bb82256d'
down_revision: Union[str, Sequence[str], None] = '6d8b5227e0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kadan_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id', name='uq_kadan_accounts_tenant_customer')
    )
    op.create_index(op.f('ix_kadan_accounts_customer_id'), 'kadan_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_kadan_accounts_status'), 'kadan_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_kadan_accounts_tenant_id'), 'kadan_accounts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kadan_accounts_tenant_id'), table_name='kadan_accounts')
    op.drop_index(op.f('ix_kadan_accounts_status'), table_name='kadan_accounts')
    op.drop_index(op.f('ix_kadan_accounts_customer_id'), table_name='kadan_accounts')
    op.drop_table('kadan_accounts')
    # ### end Alembic commands ###