"""update billing models

Revision ID: f7955749ce29
Revises: 06b9c5ed4f91
Create Date: 2026-09-16 23:30:53.318702
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f7955749ce29'
down_revision: Union[str, Sequence[str], None] = '06b9c5ed4f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_items', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.alter_column('bill_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('bill_items', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.add_column('bills', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bills', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('bills', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.create_unique_constraint('uq_bills_tenant_bill_number', 'bills', ['tenant_id', 'bill_number'])
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_index(op.f('ix_categories_status'), 'categories', ['status'], unique=False)
    op.alter_column('product_variants', 'package_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('product_variants', 'unit',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('product_variants', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_variants', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('product_variants', 'unit',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('product_variants', 'package_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.drop_index(op.f('ix_categories_status'), table_name='categories')
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint('uq_bills_tenant_bill_number', 'bills', type_='unique')
    op.alter_column('bills', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('bills', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_column('bills', 'updated_at')
    op.alter_column('bill_items', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('bill_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_column('bill_items', 'tax_rate')
    # ### end Alembic commands ###